### ISSUE TITLE
Improve failure message when .terraform.lock.hcl version is more than a major version out of date

### ISSUE THREAD

**Issue by azarudeena** [tfverch/tfvc#48]
When using wild cards, even though latest match and latest Overall matches. it's still flagging as outdated. PFB 
```
terraform {
  required_version = ">= 1.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.0"
    }
    sops = {
      source  = "carlpett/sops"
      version = "~> 0.5"
    }
  }
}

```

```
❯ tfvc .

provider 'hashicorp/aws' FAILED Outdated major version
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  Resolution
  ───────────────────────────────────────────────────────────────────────
  Consider migrating to the latest major version of this provider

  Details
  ────────────────────────────────────────────────────────
  Type:                provider
  Path:                .
  Name:                hashicorp/aws
  Source:              registry.terraform.io/hashicorp/aws
  Version Constraints: ~> 4.0
  Version:             3.75.2
  Latest Match:        4.37.0
  Latest Overall:      4.37.0

```

**Comment by azarudeena** [comment]
Same thing if I use the clear version of `4.37.0` it's working as expected

**Comment by ryan-jan** [comment]
@azarudeena the `Version` is `3.75.2`. This is pulled from the `.terraform.lock.hcl` file. This is failing because even though your version constraint is configured to allow v4, your lock file is still out of date. You need to run `terraform init -upgrade` to actually pull in the latest versions of providers into your lock file. 

I do agree that this resolution text could be improved to explain the failure a bit better.

**Comment by azarudeena** [comment]
Yes @ryan-jan  it worked after using the `-upgrade` thanks for considering.
